module.exports = {
    TOAST: 'TOAST',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',

    SET_FILTER_START: 'SET_FILTER_START',
    SET_FILTER_START_NOW: 'SET_FILTER_START_NOW',
    CHANGE_FILTER_START: 'CHANGE_FILTER_START',
    SET_FILTER_UNIT: 'SET_FILTER_UNIT',

    SET_GROSSES: 'SET_GROSSES',
    UPDATE_GROSS: 'UPDATE_GROSS'
};
